### ISSUE TITLE
Change Marker Icon to Github profile image 

### ISSUE THREAD

**Issue by matteomessmer** [matteomessmer/hacktoberfest#12]
It would be cool to use the profile image of the contributors as markers on the map.

**Comment by adlyloukil** [comment]
i'll work on this.

**Comment by himanshupawar-10** [comment]
I would like to work on this.

**Comment by matteomessmer** [comment]
ok, I'll assign you, the objective is to have for each marker the right photo. For example, my marker should have my profile pic. In the list of the positions there are the usernames associated to the coordinates.
