### ISSUE TITLE
'Image of Hacktoberfest' is Broken in README.md

### ISSUE THREAD

**Issue by saurabhhere** [matteomessmer/hacktoberfest#26]
The image of Hacktoberfest is not showing in README.md

![Capture](https://user-images.githubusercontent.com/60233336/97089243-26dcca80-1654-11eb-9e95-783ae978be0a.PNG)

I can send a PR on this if you tell which image to add here.
Thanks :)

**Comment by matteomessmer** [comment]
Ok it was the hacktoberfest 2020 image you can find in most hacktoberfest repositories
