### ISSUE TITLE
Change OSM Map style

### ISSUE THREAD

**Issue by matteomessmer** [matteomessmer/hacktoberfest#3]
Add an option to switch between two styles for the map (a switch button should make the job)
The two styles could be a Halloween theme and a Dark theme.

**Comment by harsh863** [comment]
@matteomessmer , can i work on it??

**Comment by matteomessmer** [comment]
Yes sure

**Comment by harsh863** [comment]
@matteomessmer it would be better if you merge #7 first then i would have some update ui, which would be easy to work on.

**Comment by matteomessmer** [comment]
Merged

**Comment by harsh863** [comment]
Thanks @matteomessmer , here is the pr of this issue #10
